/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void TestButton_click1(GButton source, GEvent event) { //_CODE_:TestButton:438955:
  println("TestButton - GButton >> GEvent." + event + level_counter+" @ " + millis());
  level_counter++;
  if (level_counter > 7) level_counter=0;
  switch(level_counter)
  {
  case 0:
    MyImg = "0.jpg";
    break;

  case 1:
    MyImg = "20.jpg";
    break;

  case 2:
    MyImg = "30.jpg";
    break;
  case 3:
    MyImg = "50.jpg";
    break;
  case 4:
    MyImg = "60.jpg";
    break;
  case 5:
    MyImg = "70.jpg";
    break;
  case 6:
    MyImg = "90.jpg";
    break;
  case 7:
    MyImg = "100.jpg";
    break;
    
    default :
     MyImg = "0.jpg";
  };
} //_CODE_:TestButton:438955:

public void Location1_click1(GImageButton source, GEvent event) { //_CODE_:Location_1:732449:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
   link("https://goo.gl/maps/kTK2TbgNhUnYcAkp8");
} //_CODE_:Location_1:732449:

public void Location2_click1(GImageButton source, GEvent event) { //_CODE_:Location2:653477:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
   link("https://goo.gl/maps/kTK2TbgNhUnYcAkp8");
} //_CODE_:Location2:653477:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  TestButton = new GButton(this, 352, 449, 80, 30);
  TestButton.setText("Test");
  TestButton.addEventHandler(this, "TestButton_click1");
  Location_1 = new GImageButton(this, 230, 439, 50, 45, new String[] { "location-icon-png-4246.png", "location-icon-png-4246.png", "location-icon-png-4246.png" } );
  Location_1.addEventHandler(this, "Location1_click1");
  Location2 = new GImageButton(this, 650, 438, 50, 45, new String[] { "location-icon-png-4246.png", "location-icon-png-4246.png", "location-icon-png-4246.png" } );
  Location2.addEventHandler(this, "Location2_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton TestButton; 
GImageButton Location_1; 
GImageButton Location2; 
